### ISSUE TITLE
Desktop-install installs server

### ISSUE THREAD

**Issue by jarmoni** [boxcutter/ubuntu#13]
I executed:
make virtualbox/ubuntu1504-desktop

but server-flavour is installed:

virtualbox-iso: Downloading or copying: http://releases.ubuntu.com/15.04/ubuntu-15.04-server-amd64.iso

**Comment by annawake** [comment]
Yes, this is intentional.  It still installs the desktop, but uses the server media.  As as Ubuntu 14.04, it's fairly impossible to automate the desktop install using the desktop media, so we had to use the server media.  I'm not aware of Ubuntu 15.04 making improvements in this area, so closing this issue as it produces the intended result (desktop is produced).  We would love to see a PR that automates the desktop install using the desktop media, if you sort it out!
