### ISSUE TITLE
Regression: Building ubuntu desktop 16.04 desktop fails when trying to apt-get update/upgrade

### ISSUE THREAD

**Issue by gae123** [boxcutter/ubuntu#141]
This regressed immediately after commit 9f3291a84ff4a25cf680b270e687eca3fba5adc3 Please see attached log files that show what happens before this commit and after this commit.
[before-success.txt](https://github.com/boxcutter/ubuntu/files/1599131/before-success.txt)
[after-failure.txt](https://github.com/boxcutter/ubuntu/files/1599130/after-failure.txt)

**Comment by dragon788** [comment]
The issue is likely due to the fact that some of the packages pulled in by `ubuntu-desktop` in the preseed will get upgraded and trigger a prompt that requires interaction. I ran into something similar though using a different preseed and for me the quick fix was adding `DEBIAN_FRONTEND=noninteractive` to the `environment_vars` block in the `ubuntu.json`.

```      "environment_vars": [
        "CLEANUP_PAUSE={{user `cleanup_pause`}}",
        "DEBIAN_FRONTEND=noninteractive",
        "DESKTOP={{user `desktop`}}",
        "UPDATE={{user `update`}}",
        <snipped>
      ],
```
