### ISSUE TITLE
ubuntu1604-desktop.json hangs

### ISSUE THREAD

**Issue by lqueryvg** [boxcutter/ubuntu#147]
ubuntu1604-desktop.json build hangs at the graphical language selection screen.

Lot's of searching suggests this is a bug in the ubuntu installer.

environment: Windows7 , Virtualbox 5.2.8, packer 1.1.3

**Comment by dragon788** [comment]
The recent merge of #145 is the culprit, #143 is the correct ISO to allow the automation to happen. I've pinged the maintainers regarding this.

**Comment by lqueryvg** [comment]
@dragon788  thanks for that. I tried with the other ISO as per #143, automated install worked and booted to graphical desktop, but ended up with terminal problems as per #121 and the suggestions there didn't fix it.

**Comment by lqueryvg** [comment]
@dragon788,

Is the root problem that the ubuntu desktop ISO doesn't work with automation ?

I.e. (to spell it out):

1. boxcutter is using the server ISO instead of the desktop ISO because the automation doesn't work with the desktop ISO
2. boxcutter then installs the unity desktop on top of the server ISO install
3. the terminal doesn't work

If the desktop ISO with the automation, then I assume these problems would go away.

Is my logic correct ?

**Comment by dragon788** [comment]
Yes, though #3 is simply an issue of a missing config option that is set in a couple of open pull requests but hasn't been merged yet. Unfortunately Canonical has no immediate plans to improve the automation of the desktop ISO from what I've seen and since installing via the server/alternate installation results in a functionally equivalent system there isn't a lot of pressure for them to change that.

**Comment by npmeyer** [comment]
FYI, I think the issue with the terminal is obsolete -- after building from master with my PR, I can open the terminal in a VirtualBox VM.
