### ISSUE TITLE
ubuntu1504-desktop.json is not generating desktop

### ISSUE THREAD

**Issue by d3netxer** [boxcutter/ubuntu#15]
ubuntu1504-desktop.json is not generating desktop GUI when I build and launch it.

Maybe because it uses the server .iso?

I tried switching out the link with the 15.04 desktop iso, but it can't finish building because the desktop GUI has a pop up menu that interrupts the build.

**Comment by annawake** [comment]
No, the use of the server ISO is intentional because AFAIK one cannot automate the install using the desktop media.  You can create a desktop install from the server media.

If you try to download the ubuntu1504-desktop images created from the ubuntu1504-desktop.json you'll see that indeed they generate a GUI desktop: https://atlas.hashicorp.com/boxcutter/boxes/ubuntu1504-desktop

All I can think of is that perhaps your local config does not support 3D acceleration, which is turned on by default in this image.  You may want to try tweaking the video display settings in https://github.com/boxcutter/ubuntu/blob/master/tpl/vagrantfile-ubuntu1504-desktop.tpl to see if that might be an issue on your machine.

**Comment by d3netxer** [comment]
Thanks @annawake. In the past I tried building ubuntu1504-desktop, but it got stuck waiting for the shh while a pop up menu displayed on the GUI. I did a pull request yesterday and built it again and it worked great this time!
