### ISSUE TITLE
When used with "public_network" default gateway is missing on boot.

### ISSUE THREAD

**Issue by GR360RY** [boxcutter/ubuntu#31]
Example `Vagrantfile`:

    Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
      config.vm.box = "boxcutter/ubuntu1404-desktop"
      config.vm.network "public_network"
    end

Routing table with `route -n` after `vagrant up`:

    vagrant@vagrant:~$ route -n
    Kernel IP routing table
    Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
    10.0.2.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
    10.100.200.0    0.0.0.0         255.255.255.0   U     0      0        0 eth1
    169.254.0.0     0.0.0.0         255.255.0.0     U     1000   0        0 eth0

The box is missing `0.0.0.0` destination.
`vagrant reload` or `reboot` fixes this issue. If provisioning is required, default gateway should be fixed with explicit provisioning script. Here is my workaround:

    $ grep vagrant_fix_default_gw.sh Vagrantfile
    config.vm.provision :shell, path: "scripts/vagrant_fix_default_gw.sh"

Script contents:

    $ cat scripts/vagrant_fix_default_gw.sh
    route del default || true
    route -n | grep -qe '^0.0.0.0' || sudo route add default gw `grep routers /var/lib/dhcp/dhclient.eth1.leases | sort -u | awk '{print $3}' | awk -F";" '{print $1}'`

This behaviour exists only with `boxcutter/ubuntu1404-desktop`. `ubuntu/trusty64` box works as expected. Probably related to NetworkManager.

It would be nice to fix it in box itself.

**Comment by dragon788** [comment]
@GR360RY I have a suspicion this is the same issue we are seeing. The desktop version installs NetworkManager which by default won't manage interfaces listed in /etc/network/interfaces which includes eth0 since this installs from the server ISO which assumes ifupdown will be used.

This breaks NetworkManager functionality because it defaults in Ubuntu to not manage any interfaces controlled by ifupdown. You can run a provision script before the final shutdown to set the below, or to remove any interfaces that aren't localhost from /etc/network/interfaces.

You could also set the below in /etc/NetworkManager/NetworkManager.conf to ignore that fact that ifupdown also knows about this interface.

    [ifupdown]
    managed=true

**Comment by dragon788** [comment]
I came up with a "nicer" sed that can be run to "hide"/comment the primary interface and any additional ones from /etc/network/interfaces so NetworkManager will manage them. I run this via one of the script/ files to allow NetworkManager to take over.

    sed -i "/^# The primary network interface/,$ s/^\([^#]\)/# \1/g"

**Comment by annawake** [comment]
Closing for now, due to the age of the issue. Reopen if still seeing the behaviour.
