### ISSUE TITLE
Ubuntu 1504.json -- Vagrant box cannot mount shared folders

### ISSUE THREAD

**Issue by hvram1** [boxcutter/ubuntu#36]
I see this in the error . The vboxadd-install.log is empty 
Uncompressing VirtualBox 4.2.12 Guest Additions for Linux............[0m
[0;32m    virtualbox-iso: VirtualBox Guest Additions installer[0m
[0;32m    virtualbox-iso: Copying additional installer modules ...[0m
[0;32m    virtualbox-iso: Installing additional modules ...[0m
[0;32m    virtualbox-iso: Removing existing VirtualBox DKMS kernel modules ...done.[0m
[0;32m    virtualbox-iso: Removing existing VirtualBox non-DKMS kernel modules ...done.[0m
[0;32m    virtualbox-iso: Building the VirtualBox Guest Additions kernel modules[0m
[0;32m    virtualbox-iso: The headers for the current running kernel were not found. If the following[0m
[0;32m    virtualbox-iso: module compilation fails then this could be the reason.[0m
[0;32m    virtualbox-iso:[0m
[0;32m    virtualbox-iso: Building the main Guest Additions module ...done.[0m
[0;32m    virtualbox-iso: Building the shared folder support module ...fail![0m
[0;32m    virtualbox-iso: (Look at /var/log/vboxadd-install.log to find out what went wrong)[0m
[0;32m    virtualbox-iso: Doing non-kernel setup of the Guest Additions ...done.[0m

**Comment by annawake** [comment]
These images do not support rebuilds to downgrade the guest additions.  Rather than trying to make the images bigger by leaving the kernel-headers, gcc & dkms installed to support kernel rebuilds (which should happen rarely), instead we make it easy for your to build images of your own should you not want to use the 5.0.x guest tools that are provided.

Just rebuild the box locally for your 4.2.12 machine, and your problem will be fixed.  Atlas does not currently provide an easy way to support multiple VirtualBox versions.  So we stick with the latest VirtualBox 5.x guest addition stream.

**Comment by hvram1** [comment]
Thanks . I upgraded by VirtualBox to 5.0 and I had an issue with packer (0.8.1 ) . ( --sataportcount not supported for VBoxManage ) . I upgraded packer to 0.8.6 and that fixed he problem
