### ISSUE TITLE
Ubuntu 15.10 Desktop missing

### ISSUE THREAD

**Issue by dusek** [boxcutter/ubuntu#41]
Only Ubuntu 12.04 and 14.04 are present in desktop variants. Ubuntu 15.10 is not (neither in the repo, nor in atlas), even though it is present as a usual configuration (server). I want to test with Ubuntu 15.10 desktop :-)

**Comment by dusek** [comment]
As Ubuntu 15.04 went missing on atlas, this means that currently the most "recent" desktop version became 14.04, which is quite old. So that together with this issue feels as creating a regression.

**Comment by dragon788** [comment]
@dusek From my brief glance at the code it appears there isn't a lot of "unique" specifications around a "desktop" vs the others. Since Ubuntu frequently changes their desktop (Unity, no Unity) it makes sense that in the script/desktop.sh they are only calling out the versions they have tested. I think it would be pretty easy to add in a 15.10 option, and I might give it a shot if I have a chance this week.

**Comment by dusek** [comment]
@dragon788 thanks, if you had a chance to give it a try, that would be awesome! 😊

**Comment by dusek** [comment]
I no longer see this as an issue since Ubuntu 16.04 has a desktop variant (as long as it makes it to Atlas someday 😄). If someone really needs specifically 15.10 version of desktop (and 16.04 does not suffice), feel free to reopen though.
