### ISSUE TITLE
ubuntu1604-desktop.json installs server image

### ISSUE THREAD

**Issue by JonasGroeger** [boxcutter/ubuntu#63]
https://github.com/boxcutter/ubuntu/blob/master/ubuntu1604-desktop.json#L10
should say
`"iso_url": "http://releases.ubuntu.com/16.04/ubuntu-16.04-desktop-amd64.iso",`

**Comment by annawake** [comment]
For previous releases, the desktop image could not be automated so the server image had to be used. Have you verified this has changed in the 16.04 release?

**Comment by d3netxer** [comment]
could we get the desktop image to work?

**Comment by tknerr** [comment]
+1

@annawake what was the reason / problem with the desktop image?

**Comment by jerryfromearth** [comment]
Here's the discussion of the problem with preseeding Ubuntu 14.04 & 16.04 desktop image:
https://github.com/mitchellh/packer/issues/3521
Basically, the desktop installer UI is different and I haven't found a way to make preseed work yet.

Here's a screenshot of preseed "typing boot command" in a desktop installer:
![boot_command](https://cloud.githubusercontent.com/assets/343557/17322238/da7ffc4e-589c-11e6-86e4-360710ca7547.png)

Frankly I prefer install-server-then-install-ubuntu-desktop approach, because ubuntu desktop includes a lot of useless programs by default that can be filtered out by "apt-get install -y --no-install-recommends ubuntu-desktop".

**Comment by annawake** [comment]
Closing out this issue as I'm not aware of a good workaround for automating the desktop install, and the server approach works.
