### ISSUE TITLE
Ansible support

### ISSUE THREAD

**Issue by joaocc** [boxcutter/ubuntu#7]
Hi,
Have you thought of adding support for using Ansible?
Thx

**Comment by annawake** [comment]
In what manner do you mean?

Currently `cmtools.sh` is there to install the agents necessary to install CM (configuration management) tools to provision the box.  The boxes themselves are intended to be JEOS (Just Enough OS) to install a configuration management tool.  It is left as an exercise to the reader to wire up `packer` to provision these JEOS boxes from the OS on up, as we don't want to maintain a bunch of provisioning scripts for all the various configuration management tools.

Since the agent for ansible is `openssh-server`, I'm not sure what else `cmtools.sh` needs to do for you to use ansible to provision these boxes.  What else are you thinking that you need?

**Comment by joaocc** [comment]
The scenario I am considering is the ability to run Ansible script inside a freshly installed machine, for provisioning, w/o being connected to a central server.
I guess this is similar to Chef Solo. If you think this is not appropriate for the intended use of BoxCutter, that is ok.
Thanks

**Comment by annawake** [comment]
Actually there is an option for the chefdk, which is a similar scenario.  Feel free to modify `cmtools.sh` to install ansible, and test to make sure it works in an image, then submit a pull request and we'll consider moving it to master.

**Comment by joaocc** [comment]
Thx! My bash skills are not that great but I can give it a try.

The recommended approach for Ubuntu is as follows for the latest version)
````
sudo apt-get install -y software-properties-common
sudo apt-add-repository -y ppa:ansible/ansible
sudo apt-get install -y ansible
````
Alternatively, it can be done via pip install
````
sudo install -y python python-pip
sudo pip install ansible
````
Can you please let me know which approach would be a better fit for boxcutter?
Thx
