### ISSUE TITLE
Shared custom-scripts tools?

### ISSUE THREAD

**Issue by mrjcleaver** [boxcutter/ubuntu#77]
It's clear (https://github.com/boxcutter/centos/issues/50) that there are many possible custom-script.sh possibilities for boxcutter.

How about a dedicated repository for such platform-sharable components?

Thanks, M.

**Comment by annawake** [comment]
Well, the hope is that most `custom-script.sh` work will be merely to call things written in Chef, Ansible, Puppet, CFEngine, etc. - configuration management systems rather than adding more scripts.

These boxes are intended to be "Just Enough Operating System" (JEOS)....for a configuration management system. So I hope there's not much that should be in `custom-script.sh` that are really shareable except in the various CM archives.
